### PR TITLE
fix indentation of code blocks in README

### PR DESCRIPTION
**Pull request by StrikerRUS**
**What this PR does / why we need it**:
Fix indentation of code blocks in README.

# Was:

image

# Now

image

<details>
<summary>DCO</summary>

Signed-off by: StrikerRUS < nekit94-08 at mail.ru >
</details>

### CODE REVIEW

**Comment by ksatchit** [comment]
Thanks for the PR @StrikerRUS ! The DCO check fails, can you ensure that the sign-off is proper. You could try this: `git reset --soft <commit-hash>` & then `git commit -s` ?

**Comment by ksatchit** [comment]
You could try this: `git reset --soft <commit-hash>` & then `git commit -s`. In you are doing this through the website, you could add this `Signed-off-by: Your name <your email-id>` in your commit,PR description.

**Comment by StrikerRUS** [comment]
@ksatchit Thanks for your response! My commit has been already signed, please see this:

image

Unfortunately, the commands you've provided didn't help:
```
D:\Users\nekit\Downloads\litmus>git reset --soft 15c8d477c1164dcef29a530aa796096636f8a831

D:\Users\nekit\Downloads\litmus>git commit -s
On branch indent
Your branch is up-to-date with 'origin/indent'.

nothing to commit, working tree clean

D:\Users\nekit\Downloads\litmus>git push origin indent
Everything up-to-date
```

**Comment by ksatchit** [comment]
Oh ! sorry for the oversight. By any chance, have you enabled the email address privacy on git, but pushed from a different ID? <just guessing why the DCO check fails>

**Comment by StrikerRUS** [comment]
@ksatchit You don't need to apologize!

I have several e-mails in my GitHub account but this one is the `Primary`. Maybe this is the case?..

image

**Comment by ksatchit** [comment]
That shouldn't cause issues, IMO. Anyways, we do have the email address. So going ahead w/ the merge!

**Pull request merged**
