### PR TITLE
refactor(pylint): refactor test-mem.py to boost up pylint score

### PR DESCRIPTION
**Pull request by rampreeth**
**What this PR does / why we need it**: This PR improves the pylint score of test-mem.py script

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ksatchit** [comment]
Hi @rampreeth - thank you for generalising & modularizing the script!  The changes look good. Can you just confirm successful execution via an run/output snippet?

**Comment by rampreeth** [comment]
Command 
python test-mem.py -t web-d4f4cf785-42n4p  -n default  -m 500 -p dispatcher      
Output
kubectl exec web-d4f4cf785-42n4p -n default -- pidof dispatcher
2.8125 MB
2.78515625 MB
2.806640625 MB
2.78515625 MB
2.78515625 MB
2.802734375 MB
2.810546875 MB
2.802734375 MB
2.8046875 MB
2.78515625 MB
Pass

**Comment by ksatchit** [comment]
Thanks @rampreeth ! Some future enhancements could be to : 

- Take the thresholds from outside too (i.e., job)
- See if there are means of getting the process mem consumption w/o using shell pipes etc., (which makes shell=True necessary now) - not sure how this is possible w/o using monitoring tools though..  

cc: @dargasudarshan @gprasath.

**Comment by rampreeth** [comment]
Sure @ksatchit , will try taking a look at those. Thanks.

**Pull request merged**
