### PR TITLE
Testing pkg kubectl

### PR DESCRIPTION
**Pull request by AndreaM16**
**What this PR does / why we need it**:
Adding tests for `pkg/kubectl`. I used [mock](https://github.com/golang/mock) to mock `Kubectl.Run` and `Exec.Output`. Test coverage of `pkg/kubectl` is ~90%.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
It fixes [issue #299 ](https://github.com/openebs/litmus/issues/299)

**Go Mock**
I built the tests using [golang/mock](https://github.com/golang/mock) and [TableDrivenTests](https://github.com/golang/go/wiki/TableDrivenTests). 

Some links other than the official documentation:
 - [gomock-tutorial](https://blog.codecentric.de/en/2017/08/gomock-tutorial/)
 - [getting-started-with-gomock](https://www.philosophicalhacker.com/post/getting-started-with-gomock/)

Go mock is particularly suitable when unit testing in isolation. It makes sense to use it when tested functions call other functions that perform complex operations that we are really interested in testing since we are in isolation. Instead, we can expect one of these functions to return certain results and make sure that we are actually testing all of the branches in the function we are aiming to test.

For instance, if we want to test `pkg/kubectl/GetPodNodes`:

```
// GetPodNodes fetches the nodes that hosts the pods. Pods are referred to
// via the provided labels
func GetPodNodes(k KubeRunner) (nodes []string, err error) {
	n, err := k.Run([]string{"get", "pods", "-o", "jsonpath='{.items[*].spec.nodeName}'"})
	if err != nil {
		return
	}

	// split the output by space
	nodes = strings.Split(n, " ")
	return
}
```
We sure want to mock `KubeRunner` and in particular `Run` to return some error or nil so that we are sure to cover both scenarios.

To mock that, we have simply to define in `pkg/kubectl`:

```
// KubeRunner interface provides the contract i.e. method signature to
// invoke commands at kubernetes cluster
type KubeRunner interface {
	// Run executes the kubectl command
	Run(args []string) (output string, err error)
}
```
 Generate the mock with `go generate` after writing `//go:generate mockgen -package kubectl -source=kubectl.go -destination kubectl_mock.go` in the same file and then write our test like:

```
func TestGetPods(t *testing.T) {

	args := []string{"get", "pods", "-o", "jsonpath='{.items[*].metadata.name}'"}

	type expected struct {
		err   error
		nodes []string
	}

	tests := map[string]struct {
		input    string
		expected *expected
	}{
		"test 101": {
			input:    "some stuff",
			expected: &expected{nodes: []string{"some", "stuff"}},
		},
		"test 201": {
			expected: &expected{err: errors.New("some running err")},
		},
	}

	for name, mock := range tests {
		t.Run(name, func(t *testing.T) {

			ctrl := gomock.NewController(t)

			defer ctrl.Finish()

			mockRunner := NewMockKubeRunner(ctrl)

			mockRunner.EXPECT().Run(args).Return(mock.input, mock.expected.err).AnyTimes()

			nodes, err := GetPods(mockRunner)

			if err != mock.expected.err {
				t.Fatalf("test '%s' failed: expected error: %s, actual error: %s", name, mock.expected.err, err)
			}

			if !reflect.DeepEqual(nodes, mock.expected.nodes) {
				t.Fatalf("test '%s' failed: expected value %v, actual value %v", name, mock.expected.nodes, nodes)
			}
		})
	}

}
```

Where with `mockRunner.EXPECT().Run(args).Return(mock.input, mock.expected.err)` we are ensuring `Run` to return our expected values.

### CODE REVIEW

**Comment by AmitKumarDas** [comment]
@AndreaM16 thanks a lot for the PR.
Will it be possible to update the PR & / commit message with:
- when to go for mock or not?
- best practices of using mock (any link will also do)?

Will mocking be possible if structs compose structs versus interfaces? e.g. if exec exposed struct only & kubectl made use of this exec struct.

**Comment by AndreaM16** [comment]
@AmitKumarDas Will update the commit. Not sure when since I'll be on holiday until the 5th of November.

**Comment by AmitKumarDas** [comment]
@prateekpandey14 @sonasingh46 @princerachit @ashishranjan738 Anyone of you have time to debug the cause of travis failure !!!!

**Comment by AndreaM16** [comment]
@AmitKumarDas updated PR description. Let me know if you need something more specific.

**Comment by AmitKumarDas** [comment]
> @AmitKumarDas updated PR description. Let me know if you need something more specific.

The description is great. I still wanted to know if above mock lib works only if interfaces are used?

**Comment by prateekpandey14** [comment]
@AndreaM16 looks like you vendored the `openebs/litmus` too,  can you run ` dep ensure -v` this will remove and flattens the dependencies

**Comment by prateekpandey14** [comment]
Closing this PR for reference #352 adding fix for travis and removing redundant dependencies

**Pull request closed without merging**
