### PR TITLE
(refactor)(yaml): decrease the delay period & increase retry count in litmus

### PR DESCRIPTION
**Pull request by mittachaitu**
**What this PR does / why we need it**:
Playbook jobs take a longer to complete due to higher wait periods b/w status checks.
This PR reduces the wait and increases retry count while maintaining overall timeouts.

Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

@dargasudarshan @gprasath @ksatchit @vishnuitta

### CODE REVIEW

**Comment by ksatchit** [comment]
@mittachaitu , firstly, apologies for making this PR wait for so long ! Curious to know how these playbooks performed when run in a test pipeline ?

**Comment by mittachaitu** [comment]
> @mittachaitu , firstly, apologies for making this PR wait for so long ! Curious to know how these playbooks performed when run in a test pipeline ?

Sure @ksatchit, I will trigger a pipeline with my branch and I will update the result.

**Comment by ksatchit** [comment]
@mittachaitu any results ? @shashank855 can you verify the feasibility of taking this into the pipelines

**Comment by mittachaitu** [comment]
@ksatchit triggered the pipeline in GKE and AWS 
GKE: https://gitlab.openebs.ci/openebs/e2e-gke/pipelines/524
AWS: https://gitlab.openebs.ci/openebs/e2e-aws/pipelines/553

**Comment by ksatchit** [comment]
Changes look fine @mittachaitu ! Please resolve the merge conflicts. It would be great if we get a better picture of pipeline results w/ these changes (i.e., w/o the multiple minor playbook failures) though! 

cc: @nsathyaseelan @shashank855  - guess we could use your help on the above.

**Pull request closed without merging**
